site_name: MkDocs Demo
dev_addr: "127.0.0.1:8001"

theme:
  name: mkdocs
  color_mode: auto
  user_color_mode_toggle: true
  highlightjs: true
  hljs_languages:
    - haskell

repo_url: https://github.com/sgillespie/mkdocs-demo
edit_uri: edit/main/docs/

nav:
  - Welcome: 'index.md'
  - 'features.md'

markdown_extensions:
  - sane_lists
  - smarty
  - toc
